### ISSUE TITLE
yaydl does not support playlists yet, resulting in weird errors.

### ISSUE THREAD

**Issue by D1Ck3n** [dertuxmalwieder/yaydl#1] opened 2021-05-06 14:08 UTC
hi, 

i came across your project when i was looking for a command line tool for video download from voe.sx. i tried to download a voe.sx and youtube video, but unfortunately it doesn't seem to work:

```
./yaydl https://www.youtube.com/watch?v=dd-dZJYwz4E
Fetching from YouTube.
Error: https://r4---sn-4g5ednss.googlevideo.com/videoplayback?expire=1620331434&ei=SveTYP3ILdWBpATu8qmYBA&ip=5.146.60.98&id=o-AG6g819X4du50aR2CnKMZVNRXOXHFy72i8kg0_DNq4ED&itag=22&source=youtube&requiressl=yes&mh=e6&mm=31%2C26&mn=sn-4g5ednss%2Csn-5hne6nsz&ms=au%2Conr&mv=m&mvi=4&pl=22&initcwndbps=1472500&vprv=1&mime=video%2Fmp4&ns=1vURrODGNxa3BwdwimkfATMF&cnr=14&ratebypass=yes&dur=2316.260&lmt=1620244524736849&mt=1620309655&fvip=4&fexp=24001373%2C24007246&c=WEB&txp=6316222&n=L-CEZ-2WwCP4G5BvM&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAMyUVWpPMOlChPHKyjgbsy498jNyksonQD1IAu0F2J-7AiAUs1pwUyg7OgBtrrwloAkAgLxwTpDX2pmKRRF8wbTAXw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgdNrBNwDgmnVEjAakEClTSIzMso59awCNczx0YUC3b5ECIAD2FVwkQOoQOd7-MIbEBjnRHVwee-K9Gje74krBhk2q: 
Dns Failed: failed to lookup address information: Name or service not known
```

```
./yaydl "https://voe.sx/5mqmzgck2jx3#tabs-482b6qc1r"
Fetching from Voe.
The video could not be found. Invalid link?
```

**Comment by dertuxmalwieder** [comment] 2021-05-06 14:33
Hi,

I know about the not-quite-perfect YouTube support. I'm not quite sure on how to confidently fix that yet. Google makes it annoyingly hard to grab anything from them. I'm sorry that I cannot give you a quick solution for that as of now. (I wish I had some help with this...)

The Voe.sx problem is different (or is it?): The README states that "Playlists are not supported yet", but your Voe.sx link leads to a video that comes as a *.m3u8* file which... is a playlist. 🤨 (Technically, it is "one file that comes as a playlist" as it is split into several files - the result is [here](https://delivery-node-amari.voe-network.net/hls/6oarm627wi33cszcryx5f3zlvejobk2g23wq7jrtuptd7eobb3k3qejbhbqa/index-v1-a1.m3u8) - and *yaydl* cannot do that *yet*.)

Fixing this would require *yaydl* to be able to download *several* files *at once* and concatenate them in the end. I'm sorry for the bad first impression my little tool made to you. I will probably rename this issue for clarity and I'll leave it open, hoping that I (or anyone?) will find the time to take care of it soon.

**Comment by D1Ck3n** [comment] 2021-05-06 14:40
thank you first for the quick response!

okay, i didn't know that the voe.sx link leads to a playlist. i thought that was the link to the one video. do you have any idea how to get the link to the one video?

Youtube was not so important to me in the first line, but I thought I mention it times in addition :D

**Comment by dertuxmalwieder** [comment] 2021-05-06 14:45
Voe does not seem to have "one video" for that - the "one video" consists of many parts, hence the described problem occurs.

**Comment by 89z** [comment] 2021-06-20 15:57
https://github.com/dertuxmalwieder/yaydl/issues/4

**Comment by 89z** [comment] 2021-06-20 16:05
I think that this issue should be closed, and #4 should be reopened. As I just tested #4 and its still failing, while this issue is either fixed, or it was something specific to the poster, and not an issue with the code:

~~~
PS C:\yaydl> cargo run https://www.youtube.com/watch?v=dd-dZJYwz4E
    Finished dev [unoptimized + debuginfo] target(s) in 0.11s
     Running `target\debug\yaydl.exe https://www.youtube.com/watch?v=dd-dZJYwz4E`
Fetching from YouTube.
⠄ [00:00:12] [>---------------------------------------] 774.66KB/159.30MB (44m)
~~~

**Comment by dertuxmalwieder** [comment] 2021-06-20 16:24
How would #4 keep track of broken playlist functionality on (e.g.) VOE?

**Comment by 89z** [comment] 2021-06-20 16:37
Three separate issues here:

## https://www.youtube.com/watch?v=dd-dZJYwz4E issue

no reproducable and should be closed

## VOE playlist issue

still valid, either rename #1 to reflect VOE only, or open new issue for VOE playlist

## 403 response issue

still valid, should reopen #4

**Comment by dertuxmalwieder** [comment] 2021-06-20 20:48
I admit that you have a point here.

**Comment by dertuxmalwieder** [comment] 2021-06-21 10:55
**Actual TODOs to fix this:**

- Add `collect_video_data()` to `SiteDefinition`. It should collect all parts of a video as bytes and, of course, display a progress bar. **This will break the API (again).**
- Add a `is_video_multipart` flag, so `main.rs` can switch between downloading from the direct URL (as it does now) and downloading from the stream (which `collect_video_data()` is intended to do). Keeping the direct URL possibility is probably a good idea, keeping things simple when they don't need to be not simple.

**Comment by dertuxmalwieder** [comment] 2022-05-26 00:17
Closing *this* ticket as the related TODOs are (ok, quite *differently* now) done. :-)

**Closed as completed by dertuxmalwieder** 2022-05-26 00:17 UTC
Labels: bug, help wanted, good first issue
